[project]
name = "devoir-1"
version = "0.1.0"
description = "IFT3700 - Devoir 1"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=24.8.0",
    "geopy>=2.4.1",
    "jupyterlab>=4.2.5",
    "numpy>=2.0.2",
    "pandas>=2.2.2",
    "scipy>=1.13.1",
]
